### ISSUE TITLE
BatchQuery sometimes triggering a 400

### ISSUE THREAD

**Issue by leighghunt** [davetimmins/Anywhere.ArcGIS#49]
Hi Dave,

This isn't a bug in your code, but I'm wondering if you've seen it or have a workaround.

I'm querying an entire hosted feature layer containing about 800K features, I'm requesting the `GlobalId` field, and another unique identifying field.

Most of the time this is working fine, but sometimes, and at random intervals (e.g. different number of loops each time), I'm getting the following error (some bits obscured by xxxx):

```
2019/03/19 11:56:11.907|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 219 |
2019/03/19 11:56:13.081|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 220 |
2019/03/19 11:56:14.239|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 221 |
2019/03/19 11:56:16.567|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 222 |
2019/03/19 11:56:19.389|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 223 |
2019/03/19 11:56:20.775|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 224 |
2019/03/19 11:56:27.789|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 225 |
2019/03/19 11:57:23.219|ERROR|xxx.DetectChanges|System.InvalidOperationException: Code 400: Cannot perform query. Invalid query parameters..
Unable to perform query. Please check your parameters.
   at Anywhere.ArcGIS.PortalGatewayBase.Get[T,TRequest](TRequest requestObject, CancellationToken ct)
   at Anywhere.ArcGIS.PortalGatewayBase.BatchQuery[T](Query queryOptions, CancellationToken ct)
   at xxx.DetectChanges.PopulateGlobalIdsIfNecessary(InputFileInstance inputFileInstance) in /Users/leigh/dev/xxxx/xxxx/DetectChanges.cs:line 835 Code 400: Cannot perform query. Invalid query parameters..
Unable to perform query. Please check your parameters.|
```

The feature service supports pagination. 

I suspect I may be overloading the server. I'm wondering about inserting a configurable delay [here](https://github.com/davetimmins/Anywhere.ArcGIS/blob/master/src/Anywhere.ArcGIS/PortalGatewayBase.cs#L271) after say 50 iterations or something like that.

Have you seen anything like this before?

**Comment by davetimmins** [comment]
I've seen that response with timeouts before. I had it in the test project but resolved it by using Polly with a retry policy. Don't think there's a way to use that for the individual requests in that BatchQuery operation currently though it may be handy to have it as an option for the Get / Post requests I think.

**Comment by leighghunt** [comment]
> I've seen that response with timeouts before. I had it in the test project but resolved it by using Polly with a retry policy. Don't think there's a way to use that for the individual requests in that BatchQuery operation currently though it may be handy to have it as an option for the Get / Post requests I think.

Good suggestion - I'll try it and report back. Cheers.

**Comment by leighghunt** [comment]
Looking good so far - I'll do some more testing and might send a PR your way in a few days if you want.

```
2019/03/21 14:54:14.951|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 269 |
2019/03/21 14:54:54.211|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 270 |
2019/03/21 14:55:49.776|WARN|xxxx.DetectChanges|Getting error whilst querying GlobalIds - retry attempt 1 in 2 seconds... |
2019/03/21 14:56:47.151|WARN|xxxx.DetectChanges|Getting error whilst querying GlobalIds - retry attempt 2 in 4 seconds... |
2019/03/21 14:57:16.116|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 271 |
2019/03/21 14:57:22.142|INFO|Anywhere.ArcGIS.PortalGatewayBase|Exceeded query transfer limit (found 2000), batching query for rest/services/xxxx/FeatureServer/0/query - loop 272 |

```
